apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-producer
  labels:
    app: evaluation-producer
    k8s-app: prometheus
spec:
  replicas: 10
  selector:
    matchLabels:
      app: evaluation-producer
  template:
    metadata:
      labels:
        app: evaluation-producer
        k8s-app: prometheus
    spec:
      containers:
      - name: evaluation-producer
        image: dreamstream/evaluation-producer:V72
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
            cpu: "1000m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: MESSAGE_AMOUNT
          value: "10000"
        - name: BATCHING_SIZE
          value: "2000"
        - name: BATCH_TIMER
          value: "5"
        - name: APPLICATION_TYPE
          value: "Dream-Stream"
        - name: TOPIC_NAME
          value: "Topic3"
        - name: DELAY_IN_MILLISECOND
          value: "100"
        - name: SCENARIO
          value: >-
            20,10,10,10,20,30,40,50,50,50,
            20,20,20,20,30,50,70,80,90,80,
            60,20,20,20,20,30,40,50,50,50,
            20,20,20,20,30,50,70,80,90,80,
            60,20,20,20,20,30,40,50,50,50,
            10,10,10,10,40,70,90,90,60,30
