apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-producer
  labels:
    app: evaluation-producer
    k8s-app: prometheus
spec:
  replicas: 4
  selector:
    matchLabels:
      app: evaluation-producer
  template:
    metadata:
      labels:
        app: evaluation-producer
        k8s-app: prometheus
    spec:
      containers:
      - name: evaluation-producer
        image: dreamstream/evaluation-producer:V58
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: MESSAGE_AMOUNT
          value: "25000"
        - name: BATCHING_SIZE
          value: "2000"
        - name: BATCH_TIMER
          value: "5"
        - name: APPLICATION_TYPE
          value: "Dream-Stream"
        - name: TOPIC_NAME
          value: "Topic3"
        - name: DELAY_IN_MILLISECOND
          value: "100"
        - name: SCENARIO
          value: >- 
            20,100,20,20,100,20,50,50,80,80,
            100,100,50,50,20,20,20,20,20,20,
            33,33,33,33,33,33,33,33,33,33,
            33,33,33,33,33,33,33,33,33,33,
            10,10,10,10,10,100,100,100,100,100,
            20,20,20,20,20,100,100,100,100,100
            
            