apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-producer
  labels:
    app: evaluation-producer
    k8s-app: prometheus
spec:
  replicas: 10
  selector:
    matchLabels:
      app: evaluation-producer
  template:
    metadata:
      labels:
        app: evaluation-producer
        k8s-app: prometheus
    spec:
      containers:
      - name: evaluation-producer
        image: dreamstream/evaluation-producer:V73
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
            cpu: "1000m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: MESSAGE_AMOUNT
          value: "10000"
        - name: BATCHING_SIZE
          value: "2000"
        - name: BATCH_TIMER
          value: "5"
        - name: APPLICATION_TYPE
          value: "Kafka"
        - name: TOPIC_NAME
          value: "Topic3"
        - name: DELAY_IN_MILLISECOND
          value: "20"
        - name: LINGER_MS
          value: "100"
        - name: SCENARIO
          value: >- 
            8,20,30,30,25,18,12,8,9,10,
            10,10,10,9,9,9,8,8,8,8,
            8,8,10,11,12,12,30,10,50,70,
            100,60,35,10,10,9,9,8,8,8,
            8,7,6,10,28,25,18,15,12,10,
            10,8,7,10,18,18,16,14,12,9