apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-producer-ds
  labels:
    app: evaluation-producer-ds
    k8s-app: prometheus
spec:
  replicas: 10
  selector:
    matchLabels:
      app: evaluation-producer-ds
  template:
    metadata:
      labels:
        app: evaluation-producer-ds
        k8s-app: prometheus
    spec:
      containers:
      - name: evaluation-producer-ds
        image: dreamstream/evaluation-producer:V73
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: MESSAGE_AMOUNT
          value: "10000"
        - name: BATCHING_SIZE
          value: "2000"
        - name: BATCH_TIMER
          value: "5"
        - name: APPLICATION_TYPE
          value: "Dream-Stream"
        - name: TOPIC_NAME
          value: "Topic3"
        - name: DELAY_IN_MILLISECOND
          value: "100"
        - name: SCENARIO
          value: >-
            10,12,16,20,25,30,25,20,14,12,
            10,20,40,40,20,10,8,7,8,9,
            10,10,20,40,70,100,95,90,70,40,
            10,20,30,30,20,15,15,13,12,12,
            12,11,10,20,30,35,32,27,25,25,
            25,20,15,15,18,20,18,15,20,28