apiVersion: v1
kind: Service
metadata:
  name: evaluation-producer-ds
  labels:
    app: evaluation-producer-ds
    k8s-app: prometheus
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: evaluation-producer-ds
  type: ClusterIP