apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-producer
  labels:
    app: evaluation-producer
    k8s-app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-producer
  template:
    metadata:
      labels:
        app: evaluation-producer
        k8s-app: prometheus
    spec:
      containers:
      - name: evaluation-producer
        image: dreamstream/evaluation-producer:V3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: MESSAGE_AMOUNT
          value: "1000"
        - name: BATCHING_SIZE
          value: "20"
        - name: BATCH_TIMER
          value: "10"
        - name: APPLICATION_TYPE
          value: "Dream-Stream"
        - name: TOPIC_NAME
          value: "Topic3"