apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-producer-kafka
  labels:
    app: evaluation-producer-kafka
    k8s-app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-producer-kafka
  template:
    metadata:
      labels:
        app: evaluation-producer-kafka
        k8s-app: prometheus
    spec:
      containers:
      - name: evaluation-producer-kafka
        image: dreamstream/evaluation-producer:V26
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: MESSAGE_AMOUNT
          value: "100000"
        - name: APPLICATION_TYPE
          value: "Kafka"
        - name: TOPIC_NAME
          value: "Topic4"
        - name: DELAY_IN_MILLISECOND
          value: "15000"