apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-producer-kafka
  labels:
    app: evaluation-producer-kafka
    k8s-app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-producer-kafka
  template:
    metadata:
      labels:
        app: evaluation-producer-kafka
        k8s-app: prometheus
    spec:
      containers:
      - name: evaluation-producer-kafka
        image: dreamstream/evaluation-producer:V56
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: MESSAGE_AMOUNT
          value: "25000"
        - name: BATCHING_SIZE
          value: "5000"
        - name: BATCH_TIMER
          value: "5"
        - name: APPLICATION_TYPE
          value: "Kafka"
        - name: TOPIC_NAME
          value: "Topic3"
        - name: DELAY_IN_MILLISECOND
          value: "100"
        - name: SCENARIO
          value: >- 
            100,100,100,100,100,100,100,100,100,100,
            100,100,100,100,100,100,100,100,100,100,
            100,100,100,100,100,100,100,100,100,100,
            100,100,100,100,100,100,100,100,100,100,
            100,100,100,100,100,100,100,100,100,100,
            100,100,100,100,100,100,100,100,100,100